version: "3"  

tasks:  
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:  
      - task: start  
  migrate:  ## Команда для миграции
    desc: "Run database migrations"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  start:  ## Команда для запуска приложения
    desc: "Run the application"
    cmds:
      - go run ./cmd/sso --config="./config/local.yaml"
  start-test:  ## Команда для запуска приложения в тестовом режиме
    desc: "Run the application in test mode"
    cmds:
      - go run ./cmd/sso --config="./config/local_tests.yaml"
  test:  ## Команда для запуска тестов
    desc: "Run tests"
    cmds:
      - go test ./tests -count=1 -v ## -count=1 чтобы не кэшировать результаты тестов